version: "3"

services:
  warp:
    image: morrispetris/warp-docker
    container_name: warp-docker
    restart: always
    ports:
      - "10801:1080"
    environment:
      - WARP_SLEEP=5
      # - WARP_LICENSE_KEY= # optional
    cap_add:
      # Docker already have them, these are for podman users
      - MKNOD
      - AUDIT_WRITE
      # additional required cap for warp, both for podman and docker
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - /home/ubuntu/warp-docker-data:/var/lib/cloudflare-warp
